#!/usr/bin/env python3

import sys
import work_common

if len(sys.argv) < 2:
    print('Error: Missing work name')
    exit(1)

work_name = sys.argv[1]

active_work = work_common.get_active_work_names()
if work_name in active_work:
    work_common.report_stop(work_name)
else:
    work_common.report_start(work_name)

